# Core

set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g mouse off
bind m set -g mouse \; display "Mouse: #{?mouse,ON,OFF}"

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 10000
set -g escape-time 0
set -g repeat-time 1000
set -g focus-events on


# Window
bind -r [ previous-window
bind -r ] next-window


# Pane resizing
bind -r H resize-pane -L 3
bind -r J resize-pane -D 3
bind -r K resize-pane -U 3
bind -r L resize-pane -R 3


# Splitting
bind _ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"


# Copying
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel


# Session
bind C command-prompt -p "New session name:" "new-session -s '%%'"


# Reload config
bind r source-file ~/.config/tmux/tmux.conf


# Status bar
set -g status-interval 5
set -g status-left-length 60
set -g status-right-length 90


# Theme
source-file -q ~/.config/theme/current/tmux.conf


# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-cpu'

## SessionX
set -g @session-bind 'o'

## Resurrect
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-stratergy-nvim 'session'

## Continuum
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

## TPM
run '~/.tmux/plugins/tpm/tpm'
