# Status bar
set -g status-style "bg=#181825,fg=#cdd6f4"

# Left - session → hostname → prefix indicator
set -g status-left "#[fg=#f38ba8,bg=default]#[fg=#1e1e2e,bg=#f38ba8,bold] #S #[fg=#f38ba8,bg=#fab387]#[fg=#1e1e2e,bg=#fab387] #h #[fg=#fab387,bg=#f9e2af]#[fg=#1e1e2e,bg=#f9e2af,bold] #{?client_prefix, ^A ,} #[fg=#f9e2af,bg=default] "

# Window 
setw -g window-status-current-format "#[fg=#181825,bg=#89b4fa]#[fg=#1e1e2e,bg=#89b4fa,bold] #I #[fg=#313244,bg=#89b4fa,bold]#[fg=#1e1e2e,bg=#89b4fa,bold] #W #[fg=#89b4fa,bg=default]"
setw -g window-status-format "#[fg=#181825,bg=#11111b]#[fg=#a6adc8,bg=#11111b] #I  #W #[fg=#11111b,bg=default]"

setw -g window-status-separator "  "
set -g window-active-style "bg=#313244"
set -g status-justify centre

# Right - mouse → uptime → cpu
set -g status-right "#[fg=#181825,bg=#a6e3a1]#[fg=#1e1e2e,bg=#a6e3a1] 󰍽 #{?mouse,ON,OFF} #[fg=#a6e3a1,bg=#89b4fa]#[fg=#1e1e2e,bg=#89b4fa]  #(uptime -p | sed -E 's/up //; s/ hours?/h/g; s/ minutes?/m/g; s/ days?/d/g; s|, | |g') #[fg=#89b4fa,bg=#b4befe]#[fg=#1e1e2e,bg=#b4befe,bold]  #{cpu_percentage} #[fg=#b4befe,bg=default]"
