set -g @my_colour1 "#11111b"     # crust — dark fg text
set -g @my_colour2 "#313244"     # surface0 — pane border
set -g @my_colour3 "#a6adc8"     # subtext0 — default status text
set -g @my_colour4 "#89b4fa"     # blue — main accent
set -g @my_colour5 "#f9e2af"     # yellow — messages/mode

set -g @my_colour6 "#cdd6f4"     # text — status-left fg 1
set -g @my_colour7 "#1e1e2e"     # base — status-left fg 2
set -g @my_colour8 "#cdd6f4"     # text — status-left fg 3
set -g @my_colour9 "#45475a"     # surface1 — status-left bg 1
set -g @my_colour10 "#f5c2e7"    # pink — status-left bg 2
set -g @my_colour11 "#585b70"    # surface2 — status-left bg 3

set -g @my_colour12 "#cdd6f4"    # text — status-right fg 1
set -g @my_colour13 "#1e1e2e"    # base — status-right fg 2
set -g @my_colour14 "#cdd6f4"    # text — status-right fg 3
set -g @my_colour15 "#45475a"    # surface1 — status-right bg 1
set -g @my_colour16 "#f38ba8"    # red — status-right bg 2
set -g @my_colour17 "#585b70"    # surface2 — status-right bg 3

set -g @my_status_bg "#181825"   # mantle — overall bar background
